@startuml "Projex-9000"

class Insegnamento

class Progetto extends Insegnamento{
    nome: String
    traccia: String
    minStudenti: int
    maxStudenti: int
    deadline: Date
    gruppi: ArrayList<Gruppo>
}

class Studente{
    matricola: String
    autenticazione: Boolean
    progetto: Progetto
    email: String
    gruppo: Gruppo

    Gruppo creaGruppo(Progetto p)
    Gruppo iscrizioneGruppo(Gruppo g)
}

class Gruppo{
    nome: String
    studenti: ArrayList<Studente>
    progetto: Progetto
    approvazione: Boolean

    Boolean autenticaGruppo(Gruppo g)
}

Studente -- Gruppo: iscrizione
Gruppo -left- Progetto: iscrizione
@enduml