@startuml
autonumber

Studente -> Gruppo ++: creaGruppo(...)
return Gruppo

Studente -> Gruppo ++: iscrizioneGruppo(...)
return Gruppo

Gruppo -> Gruppo++: autenticazioneGruppo(...)
return Gruppo

@enduml